name = "grade-entry-system"
main = "src/index.ts"
compatibility_date = "2024-11-14"

compatibility_flags = [ "nodejs_compat" ]

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[[d1_databases]]
binding = "DB"
database_name = "grade-entry-system"
database_id = "67d6c5cf-6c74-4f23-baba-6bbb05121677"

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1